services:
  - type: web
    name: pokergame
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://pokergame-2.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: CI
        value: "false" 